--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t cve-services/cveawg --file docker/Dockerfile ."
      - "docker tag cve-services/cveawg cve-services/cveawg:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push cve-services/cveawg:latest"
  pre_build: 
    commands: 
version: 0.1
